const baseBallData = {
  'leader_hitting_repeater': {
    'copyRight': ' Copyright 2020 MLB Advanced Media, L.P.  Use of any content on this page acknowledges agreement to the terms posted here http://gdx.mlb.com/components/copyright.txt  ',
    'leader_hitting_mux': {
      'sort_column': '\'ab\'',
      'queryResults': {
        'created': '2020-06-12T17:13:00',
        'totalSize': '5',
        'row': [
          {
            'gidp': '8',
            'sac': '3',
            'np': '2539',
            'name_display_first_last': 'Ender Inciarte',
            'pos': 'CF',
            'rank': '1',
            'tb': '271',
            'gidp_opp': '57',
            'team_brief': 'Braves',
            'sport_id': '1',
            'name_display_last_init': 'Inciarte, E',
            'bb': '49',
            'avg': '.304',
            'slg': '.409',
            'ops': '.759',
            'hbp': '0',
            'team_abbrev': 'ATL',
            'so': '94',
            'wo': '1',
            'league_id': '104',
            'sf': '4',
            'team': 'atl',
            'league': 'NL',
            'cs': '9',
            'go_ao': '1.27',
            'sb': '22',
            'last_name': 'Inciarte',
            'player_id': '542255',
            'ibb': '3',
            'player_qualifier': '718',
            'roe': '3',
            'team_id': '144',
            'go': '214',
            'hr': '11',
            'minimum_qualifier': '502',
            'gdp': '8',
            'name_display_roster': 'Inciarte, Ender',
            'qualifies': 'Y',
            'rbi': '57',
            'lob': '190',
            'babip': '.339',
            'name_first': 'Ender',
            'bats': 'L',
            'xbh': '43',
            'g': '157',
            'd': '27',
            'team_name': 'Atlanta Braves',
            'sport': 'MLB',
            'tpa': '718',
            'name_display_last_first': 'Inciarte, Ender',
            'h': '201',
            'obp': '.350',
            't': '5',
            'ao': '168',
            'r': '93',
            'ab': '662',
            'name_last': 'Inciarte'
          },
          {
            'gidp': '7',
            'sac': '2',
            'np': '2397',
            'name_display_first_last': 'Dee Gordon',
            'pos': '2B',
            'rank': '2',
            'tb': '245',
            'gidp_opp': '69',
            'team_brief': 'Marlins',
            'sport_id': '1',
            'name_display_last_init': 'Gordon, D',
            'bb': '25',
            'avg': '.308',
            'slg': '.375',
            'ops': '.716',
            'hbp': '10',
            'team_abbrev': 'MIA',
            'so': '93',
            'wo': '1',
            'league_id': '104',
            'sf': '4',
            'team': 'mia',
            'league': 'NL',
            'cs': '16',
            'go_ao': '1.98',
            'sb': '60',
            'last_name': 'Gordon',
            'player_id': '543829',
            'ibb': '0',
            'player_qualifier': '695',
            'roe': '4',
            'team_id': '146',
            'go': '247',
            'hr': '2',
            'minimum_qualifier': '502',
            'gdp': '7',
            'name_display_roster': 'Gordon, Dee',
            'qualifies': 'Y',
            'rbi': '33',
            'lob': '180',
            'babip': '.354',
            'name_first': 'Dee',
            'bats': 'L',
            'xbh': '31',
            'g': '158',
            'd': '20',
            'team_name': 'Miami Marlins',
            'sport': 'MLB',
            'tpa': '695',
            'name_display_last_first': 'Gordon, Dee',
            'h': '201',
            'obp': '.341',
            't': '9',
            'ao': '125',
            'r': '114',
            'ab': '653',
            'name_last': 'Gordon'
          },
          {
            'gidp': '11',
            'sac': '5',
            'np': '2727',
            'name_display_first_last': 'Francisco Lindor',
            'pos': 'SS',
            'rank': '3',
            'tb': '329',
            'gidp_opp': '86',
            'team_brief': 'Indians',
            'sport_id': '1',
            'name_display_last_init': 'Lindor, F',
            'bb': '60',
            'avg': '.273',
            'slg': '.505',
            'ops': '.842',
            'hbp': '4',
            'team_abbrev': 'CLE',
            'so': '93',
            'wo': '1',
            'league_id': '103',
            'sf': '3',
            'team': 'cle',
            'league': 'AL',
            'cs': '3',
            'go_ao': '0.85',
            'sb': '15',
            'last_name': 'Lindor',
            'player_id': '596019',
            'ibb': '6',
            'player_qualifier': '723',
            'roe': '6',
            'team_id': '114',
            'go': '183',
            'hr': '33',
            'minimum_qualifier': '502',
            'gdp': '11',
            'name_display_roster': 'Lindor, Francisco',
            'qualifies': 'Y',
            'rbi': '89',
            'lob': '229',
            'babip': '.275',
            'name_first': 'Francisco',
            'bats': 'S',
            'xbh': '81',
            'g': '159',
            'd': '44',
            'team_name': 'Cleveland Indians',
            'sport': 'MLB',
            'tpa': '723',
            'name_display_last_first': 'Lindor, Francisco',
            'h': '178',
            'obp': '.337',
            't': '4',
            'ao': '216',
            'r': '99',
            'ab': '651',
            'name_last': 'Lindor'
          },
          {
            'gidp': '4',
            'sac': '3',
            'np': '2884',
            'name_display_first_last': 'Charlie Blackmon',
            'pos': 'RF',
            'rank': '4',
            'tb': '387',
            'gidp_opp': '54',
            'team_brief': 'Rockies',
            'sport_id': '1',
            'name_display_last_init': 'Blackmon, C',
            'bb': '65',
            'avg': '.331',
            'slg': '.601',
            'ops': '1.000',
            'hbp': '10',
            'team_abbrev': 'COL',
            'so': '135',
            'wo': '0',
            'league_id': '104',
            'sf': '3',
            'team': 'col',
            'league': 'NL',
            'cs': '10',
            'go_ao': '1.00',
            'sb': '14',
            'last_name': 'Blackmon',
            'player_id': '453568',
            'ibb': '9',
            'player_qualifier': '725',
            'roe': '9',
            'team_id': '115',
            'go': '153',
            'hr': '37',
            'minimum_qualifier': '502',
            'gdp': '4',
            'name_display_roster': 'Blackmon, Charlie',
            'qualifies': 'Y',
            'rbi': '104',
            'lob': '150',
            'babip': '.371',
            'name_first': 'Charlie',
            'bats': 'L',
            'xbh': '86',
            'g': '159',
            'd': '35',
            'team_name': 'Colorado Rockies',
            'sport': 'MLB',
            'tpa': '725',
            'name_display_last_first': 'Blackmon, Charlie',
            'h': '213',
            'obp': '.399',
            't': '14',
            'ao': '153',
            'r': '137',
            'ab': '644',
            'name_last': 'Blackmon'
          },
          {
            'gidp': '18',
            'sac': '1',
            'np': '2547',
            'name_display_first_last': 'Elvis Andrus',
            'pos': 'SS',
            'rank': '5',
            'tb': '303',
            'gidp_opp': '118',
            'team_brief': 'Rangers',
            'sport_id': '1',
            'name_display_last_init': 'Andrus, E',
            'bb': '38',
            'avg': '.297',
            'slg': '.471',
            'ops': '.808',
            'hbp': '3',
            'team_abbrev': 'TEX',
            'so': '101',
            'wo': '1',
            'league_id': '103',
            'sf': '4',
            'team': 'tex',
            'league': 'AL',
            'cs': '10',
            'go_ao': '1.23',
            'sb': '25',
            'last_name': 'Andrus',
            'player_id': '462101',
            'ibb': '0',
            'player_qualifier': '689',
            'roe': '7',
            'team_id': '140',
            'go': '206',
            'hr': '20',
            'minimum_qualifier': '502',
            'gdp': '18',
            'name_display_roster': 'Andrus, Elvis',
            'qualifies': 'Y',
            'rbi': '88',
            'lob': '234',
            'babip': '.325',
            'name_first': 'Elvis',
            'bats': 'R',
            'xbh': '68',
            'g': '158',
            'd': '44',
            'team_name': 'Texas Rangers',
            'sport': 'MLB',
            'tpa': '689',
            'name_display_last_first': 'Andrus, Elvis',
            'h': '191',
            'obp': '.337',
            't': '4',
            'ao': '168',
            'r': '100',
            'ab': '643',
            'name_last': 'Andrus'
          }
        ]
      }
    }
  }
};

export default baseBallData;
